USE gamelounge;

CREATE TABLE IF NOT EXISTS Accounts(
Aid INT AUTO_INCREMENT NOT NULL,
Username VARCHAR(30) NOT NULL,
Pass VARCHAR(30) NOT NULL,
Abudget FLOAT NULL,
Cid INT NOT NULL,
PRIMARY KEY (Aid));

CREATE TABLE IF NOT EXISTS Customers(
Cid INT AUTO_INCREMENT NOT NULL,
Cname VARCHAR(30) NULL,
Cgender CHAR NULL,
Cbirthday DATE NULL,
PRIMARY KEY (Cid));

CREATE TABLE IF NOT EXISTS Device(
Did INT AUTO_INCREMENT NOT NULL,
Dtype VARCHAR(30) NOT NULL,
Eid INT NOT NULL,
PRIMARY KEY (Did));

CREATE TABLE IF NOT EXISTS DeviceType(
Dtype VARCHAR(30),
Dprice FLOAT NOT NULL,
Dcharge FLOAT NOT NULL,
PRIMARY KEY (Dtype));

CREATE TABLE IF NOT EXISTS Employee(
Eid INT AUTO_INCREMENT NOT NULL,
Ename VARCHAR(30) NOT NULL,
Esalary FLOAT NOT NULL,
PRIMARY KEY (Eid));

CREATE TABLE IF NOT EXISTS Game(
Gname VARCHAR(30) NOT NULL,
Gdeveloper VARCHAR(30) NULL,
time_played FLOAT NULL,
PRIMARY KEY (Gname));

CREATE TABLE IF NOT EXISTS GameComp(
Dtype VARCHAR(30) NOT NULL,
Gname VARCHAR(30) NOT NULL);

CREATE TABLE IF NOT EXISTS Bills(
Bid INT AUTO_INCREMENT NOT NULL,
Bdate DATE NOT NULL,
Bprice FLOAT NOT NULL,
Aid INT NOT NULL,
PRIMARY KEY (Bid));

CREATE TABLE IF NOT EXISTS Items(
itemId INT AUTO_INCREMENT NOT NULL,
Bid INT NOT NULL,
itemname VARCHAR(30),
itemtype VARCHAR(30) NOT NULL,
Qty INT NOT NULL,
Aid INT NOT NULL,
Itemprice FLOAT NOT NULL,
PRIMARY KEY (itemId)
);

CREATE TABLE IF NOT EXISTS Playing(
Pid INT AUTO_INCREMENT NOT NULL,
Start_time VARCHAR(30) NOT NULL,
End_Time VARCHAR(30) NULL,
Did INT NOT NULL,
Gname VARCHAR(30) NOT NULL,
Aid INT NOT NULL,
Eid INT NOT NULL,
Earning FLOAT NOT NULL,
PRIMARY KEY (Pid));

CREATE TABLE IF NOT EXISTS Suppliers(
Sname VARCHAR(30) NOT NULL,
Stransaction FLOAT NOT NULL,
PRIMARY KEY (Sname));

CREATE TABLE IF NOT EXISTS Food(
Pdid INT NOT NULL,
Fqtyleft INT NULL,
Fexpirydate DATE NOT NULL,
Fprice FLOAT NOT NULL,
Fname VARCHAR(30) NOT NULL,
PRIMARY KEY (Fname,Pdid));

CREATE TABLE IF NOT EXISTS FoodComp(
Dtype VARCHAR(30) NOT NULL,
Fname VARCHAR(30) NOT NULL);

CREATE TABLE IF NOT EXISTS Purchases_Header(
Phid INT AUTO_INCREMENT NOT NULL,
Totalcost FLOAT NOT NULL,
Purchasedate DATE NOT NULL,
Sname VARCHAR(30) NOT NULL,
PRIMARY KEY (Phid));

CREATE TABLE IF NOT EXISTS Purchases_Details(
Pdid INT AUTO_INCREMENT NOT NULL,
Phid INT NOT NULL,
Costperitem FLOAT NOT NULL,
Expirydate DATE NOT NULL,
ItemQty INT NOT NULL,
ItemName VARCHAR(30) NOT NULL,
PRIMARY KEY (Pdid));

